version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Expose backend on port 3001
    volumes:
      - ./backend:/app
    environment:
      - NAME=jovanfidello  
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose frontend on port 3000
    volumes:
      - ./frontend:/app
    environment:
      - NAME=jovanfidello  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
